CREATE EVENT open_event ON SCHEDULE EVERY 1 MINUTE DO BEGIN
UPDATE event
SET state = 'OPEN'
WHERE CURRENT_TIMESTAMP >= start_time
  AND CURRENT_TIMESTAMP < end_time;
END;
CREATE EVENT close_event ON SCHEDULE EVERY 1 MINUTE DO BEGIN
UPDATE event
SET state = 'CLOSED'
WHERE CURRENT_TIMESTAMP >= end_time;
END;